# Updating and patcinig Ubuntu servers
# Usage: ansible-playbook -i hosts ubuntu_update.yml 
---
- hosts: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=3600
    
    - name: remove apt lock file
      file:
        path: /var/lib/dpkg/lock
        state: absent
      when: ansible_distribution == "Ubuntu"

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Check if a reboot is required.
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_md5: no
      register: reboot_required_file  

    - name: reboot the server if a restart is required by apt
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true
        
    - name: Remove dependency packages no longer required
      ansible.builtin.apt:
       autoremove: yes
       